COLUMN_MAPPING_Location = {
    "Location": [
        "final location",
    ],
    "broad property types Share (%)": [
        "residential share (in %)",
        "commercial share (in %)",
        "others share (in %)",
        "residential+commercial share (in %)",
    ],
    "Total Project Launched": [
        "total projects commenced",
    ],
    "Total Phases Launched": [
        "total no.of rera entry",
    ],
    "Total Buildings or Towers": [
        "total no. of blocks (based of projects)",
    ],
    "Total property type wise projects": [
        "no. of residential projects",
        "no. of commercial projects",
        "no. of others projects",
        "residential+commercial",
        "no. of indusrial projects",
    ],
    "Total units sold": [
        "total sold - igr",
    ],
    "Property type wise Units Sold": [
        "flat_sold - igr",
        "office_sold - igr",
        "others_sold - igr",
        "shop_sold - igr",
    ],
    "broad property types wise unit sold": [
        "commercial_sold - igr",
        "other_sold - igr",
        "residential_sold - igr",
    ],
    "BHK types wise units sold": [
        "1.5bhk_sold - igr",
        "1bhk_sold - igr",
        "2.25bhk_sold - igr",
        "2.5bhk_sold - igr",
        "2.75bhk_sold - igr",
        "2bhk_sold - igr",
        "3bhk_sold - igr",
        "<1bhk_sold - igr",
        ">3bhk_sold - igr",
    ],
    "Total Carpet Area sold or consumed in sqft": [
        "total carpet area consumed (sqft) - igr",
    ],
    "Property Type wise Carpet area sold or consumed in sqft": [
        "flat_carpet_area_consumed(in sqft) - igr",
        "office_carpet_area_consumed(in sqft) - igr",
        "others_carpet_area_consumed(in sqft) - igr",
        "shop_carpet_area_consumed(in sqft) - igr",
    ],
    "BHK wise Carpet Area  sold or consumed in sqft": [
        "1.5bhk_carpet_area_consumed(in sqft) - igr",
        "1bhk_carpet_area_consumed(in sqft) - igr",
        "2.25bhk_carpet_area_consumed(in sqft) - igr",
        "2.5bhk_carpet_area_consumed(in sqft) - igr",
        "2.75bhk_carpet_area_consumed(in sqft) - igr",
        "2bhk_carpet_area_consumed(in sqft) - igr",
        "3bhk_carpet_area_consumed(in sqft) - igr",
        "<1bhk_carpet_area_consumed(in sqft) - igr",
        ">3bhk_carpet_area_consumed(in sqft) - igr",
    ],
    "broad  Property Type wise Carpet area  sold or consumed in sqft": [
        "residential_carpet_area_consumed(in sqft) - igr",
        "commercial_carpet_area_consumed(in sqft) - igr",
        "other_carpet_area_consumed(in sqft) - igr",
    ],
    "Property type wise Average Carpet Area in sqft": [
        "flat - avg carpet area (in sqft)",
        "others - avg carpet area (in sqft)",
        "office - avg carpet area (in sqft)",
        "shop - avg carpet area (in sqft)",
    ],
    "BHK wise Average Carpet Area in sqft": [
        "<1bhk - avg carpet area (in sqft)",
        "1bhk - avg carpet area (in sqft)",
        "1.5bhk - avg carpet area (in sqft)",
        "2bhk - avg carpet area (in sqft)",
        "2.25bhk - avg carpet area (in sqft)",
        "2.5bhk - avg carpet area (in sqft)",
        "2.75bhk - avg carpet area (in sqft)",
        "3bhk - avg carpet area (in sqft)",
        ">3bhk - avg carpet area (in sqft)",
    ],
    "Property type wise Carpet Area range wise Units sold": [
        "others - area range unit sold",
        "flat - area range unit sold",
        "office - area range unit sold",
        "shop - area range unit sold",
    ],
    "BHK wise Carpet Area range wise Units sold": [
        "1.5bhk - area range unit sold",
        "1bhk - area range unit sold",
        "2.5bhk - area range unit sold",
        "2bhk - area range unit sold",
        "3bhk - area range unit sold",
        "<1bhk - area range unit sold",
        ">3bhk - area range unit sold",
        "2.25bhk - area range unit sold",
        "2.75bhk - area range unit sold",
    ],
    "Property type wise Carpet area range wise Total sales (INR)": [
        "others - area range total sales",
        "flat - area range total sales",
        "office - area range total sales",
        "shop - area range total sales",
    ],
    "BHK wise Carpet area range wise Total sales(INR)": [
        "1.5bhk - area range total sales",
        "1bhk - area range total sales",
        "2.5bhk - area range total sales",
        "2bhk - area range total sales",
        "3bhk - area range total sales",
        "<1bhk - area range total sales",
        ">3bhk - area range total sales",
        "2.25bhk - area range total sales",
        "2.75bhk - area range total sales",
    ],
    "Property type wise carpet area range wise Carpet area  sold or consumed in sqft": [
        "others - area range carpet area consumed in sqft",
        "flat - area range carpet area consumed in sqft",
        "office - area range carpet area consumed in sqft",
        "shop - area range carpet area consumed in sqft",
    ],
    "BHK wise carpet area range wise carpet area  sold or consumed in sqft": [
        "1.5bhk - area range carpet area consumed in sqft",
        "1bhk - area range carpet area consumed in sqft",
        "2.5bhk - area range carpet area consumed in sqft",
        "2bhk - area range carpet area consumed in sqft",
        "3bhk - area range carpet area consumed in sqft",
        "<1bhk - area range carpet area consumed in sqft",
        ">3bhk - area range carpet area consumed in sqft",
        "2.25bhk - area range carpet area consumed in sqft",
        "2.75bhk - area range carpet area consumed in sqft",
    ],
    "Property type wise Top 10 Buyer Pincode": [
        "flat - pincode wise unit sold",
        "others - pincode wise unit sold",
        "office - pincode wise unit sold",
        "shop - pincode wise unit sold",
    ],
    "BHK wise Top 10 Buyer Pincode": [
        "<1bhk - pincode wise unit sold",
        "1bhk - pincode wise unit sold",
        "1.5bhk - pincode wise unit sold",
        "2bhk - pincode wise unit sold",
        "2.25bhk - pincode wise unit sold",
        "2.5bhk - pincode wise unit sold",
        "2.75bhk - pincode wise unit sold",
        "3bhk - pincode wise unit sold",
        ">3bhk - pincode wise unit sold",
    ],
    "Property type wise Age Range wise unit sold": [
        "flat - age range wise unit sold",
        "others - age range wise unit sold",
        "office - age range wise unit sold",
        "shop - age range wise unit sold",
    ],
    "BHK wise Age Range wise units sold": [
        "<1bhk - age range wise unit sold",
        "1bhk - age range wise unit sold",
        "1.5bhk - age range wise unit sold",
        "2bhk - age range wise unit sold",
        "2.25bhk - age range wise unit sold",
        "2.5bhk - age range wise unit sold",
        "2.75bhk - age range wise unit sold",
        "3bhk - age range wise unit sold",
        ">3bhk - age range wise unit sold",
    ],
    "Property type wise Top 10 Buyer Pincode wise Total sales (INR)": [
        "flat - pincode wise total sales",
        "others - pincode wise total sales",
        "office - pincode wise total sales",
        "shop - pincode wise total sales",
    ],
    "BHK wise Top 10 Buyer Pincode wise Total sales (INR)": [
        "<1bhk - pincode wise total sales",
        "1bhk - pincode wise total sales",
        "1.5bhk - pincode wise total sales",
        "2bhk - pincode wise total sales",
        "2.25bhk - pincode wise total sales",
        "2.5bhk - pincode wise total sales",
        "2.75bhk - pincode wise total sales",
        "3bhk - pincode wise total sales",
        ">3bhk - pincode wise total sales",
    ],
    "Property type wise Top 10 Buyer Pincode wise Carpet Area sold or consumed in sqft": [
        "flat - pincode wise carpet area consumed in sqft",
        "others - pincode wise carpet area consumed in sqft",
        "office - pincode wise carpet area consumed in sqft",
        "shop - pincode wise carpet area consumed in sqft",
    ],
    "BHK wise Top 10 Buyer Pincode wise Carpet Area  sold or consumed in sqft": [
        "<1bhk - pincode wise carpet area consumed in sqft",
        "1bhk - pincode wise carpet area consumed in sqft",
        "1.5bhk - pincode wise carpet area consumed in sqft",
        "2bhk - pincode wise carpet area consumed in sqft",
        "2.25bhk - pincode wise carpet area consumed in sqft",
        "2.5bhk - pincode wise carpet area consumed in sqft",
        "2.75bhk - pincode wise carpet area consumed in sqft",
        "3bhk - pincode wise carpet area consumed in sqft",
        ">3bhk - pincode wise carpet area consumed in sqft",
    ],
    "Property type wise Age Range wise Carpet Area  sold or consumed in sqft": [
        "flat - age range wise carpet area consumed in sqft",
        "others - age range wise carpet area consumed in sqft",
        "office - age range wise carpet area consumed in sqft",
        "shop - age range wise carpet area consumed in sqft",
    ],
    "Top buyer pincode": [
        "top_buyer_pincode",
    ],
    "Top 10 Buyer Pincode units sold": [
        "top10_buyer_in_locality",
    ],
    "BHK wise Age Range wise Total sales (INR)": [
        "<1bhk - age range wise total sales",
        "1bhk - age range wise total sales",
        "1.5bhk - age range wise total sales",
        "2bhk - age range wise total sales",
        "2.25bhk - age range wise total sales",
        "2.5bhk - age range wise total sales",
        "2.75bhk - age range wise total sales",
        "3bhk - age range wise total sales",
        ">3bhk - age range wise total sales",
    ],
    "Property type wise Age Range wise Total sales (INR)": [
        "flat - age range wise total sales",
        "others - age range wise total sales",
        "office - age range wise total sales",
        "shop - age range wise total sales",
    ],
    "BHK wise Age Range wise Carpet Area  sold or consumed in sqft": [
        "<1bhk - age range wise carpet area consumed in sqft",
        "1bhk - age range wise carpet area consumed in sqft",
        "1.5bhk - age range wise carpet area consumed in sqft",
        "2bhk - age range wise carpet area consumed in sqft",
        "2.25bhk - age range wise carpet area consumed in sqft",
        "2.5bhk - age range wise carpet area consumed in sqft",
        "2.75bhk - age range wise carpet area consumed in sqft",
        "3bhk - age range wise carpet area consumed in sqft",
        ">3bhk - age range wise carpet area consumed in sqft",
    ],
    "Property Type wise Average Price (INR)": [
        "flat- avg agreement price",
        "office- avg agreement price",
        "others- avg agreement price",
        "shop- avg agreement price",
    ],
    "Total sales (INR)": [
        "total_sales - igr",
    ],
    "Property Type wise Total Sales (INR)": [
        "flat- total agreement price",
        "office- total agreement price",
        "others- total agreement price",
        "shop- total agreement price",
    ],
    "BHK wise Total Sales (INR)": [
        "1.5bhk- total agreement price",
        "1bhk- total agreement price",
        "2.25bhk- total agreement price",
        "2.5bhk- total agreement price",
        "2.75bhk- total agreement price",
        "2bhk- total agreement price",
        "3bhk- total agreement price",
        "<1bhk- total agreement price",
        ">3bhk- total agreement price",
    ],
    "BHK wise Average Price (INR)": [
        "1.5bhk- avg agreement price",
        "1bhk- avg agreement price",
        "2.25bhk- avg agreement price",
        "2.5bhk- avg agreement price",
        "2.75bhk- avg agreement price",
        "2bhk- avg agreement price",
        "3bhk- avg agreement price",
        "<1bhk- avg agreement price",
        ">3bhk- avg agreement price",
    ],
    "Broad Property category wise Total sales (INR)": [
        "commercial- total agreement price",
        "other- total agreement price",
        "residential- total agreement price",
    ],
    "Property Type Wise Percentile's Price per Sq. Ft. (Carpet Area Basis)": [
        "flat - 50th percentile rate",
        "flat - 75th percentile rate",
        "flat - 90th percentile rate",
        "office - 50th percentile rate",
        "others - 50th percentile rate",
        "shop - 50th percentile rate",
        "office - 75th percentile rate",
        "others - 75th percentile rate",
        "shop - 75th percentile rate",
        "office - 90th percentile rate",
        "others - 90th percentile rate",
        "shop - 90th percentile rate",
    ],
    "Location coordinates (Latitude- lat, Longitude- lng)": [
        "loc_lat",
        "loc_lng",
    ],
    "Total units sold as per premanual": [
        "total_count - premamnual",
    ],
    "total sold units sold according to RERA": [
        "total sold",
    ],
    "total unsold units according to RERA": [
        "total unsold",
    ],
    "Property type wise units sold as per premanual": [
        "apartment_count - premamnual",
        "bunglow_count - premamnual",
        "chawl_count - premamnual",
        "flat_count - premamnual",
        "commercial_count - premamnual",
        "flat/shop_count - premamnual",
        "not available_count - premamnual",
        "office_count - premamnual",
        "room_count - premamnual",
        "row_house_count - premamnual",
        "shop_count - premamnual",
        "warehouse_count - premamnual",
    ],
    "Property Type wise total sold units according to rera": [
        "flat sold - rera",
        "shop sold - rera",
        "office sold - rera",
        "others sold - rera",
    ],
    "Property Type wise total unsold units": [
        "flat total unsold",
        "shop total unsold",
        "office total unsold",
        "others total unsold",
    ],
    "BHK wise total sold units according to rera": [
        "<1bhk sold - rera",
        "1bhk sold - rera",
        "1.5bhk sold - rera",
        "2bhk sold - rera",
        "2.25bhk sold - rera",
        "2.5bhk sold - rera",
        "2.75bhk sold - rera",
        "3bhk sold - rera",
        ">3bhk sold - rera",
    ],
    "BHK wise total unsold units": [
        "<1bhk total unsold",
        "1bhk total unsold",
        "1.5bhk total unsold",
        "2bhk total unsold",
        "2.25bhk total unsold",
        "2.5bhk total unsold",
        "2.75bhk total unsold",
        "3bhk total unsold",
        ">3bhk total unsold",
    ],
    "Property category wise Average Price (INR)": [
        "commercial- avg agreement price",
        "other- avg agreement price",
        "residential- avg agreement price",
    ],
    "Property Type Wise Average Price per Sq. Ft. (Carpet Area Basis)": [
        "flat - weighted average rate",
        "office - weighted average rate",
        "others - weighted average rate",
        "shop - weighted average rate",
    ],
    "Property Type wise Most Prevailing Price per Sq.Ft. Range (Rupees per sq foot)": [
        "flat - most prevailing rate - range",
        "office - most prevailing rate - range",
        "others - most prevailing rate - range",
        "shop - most prevailing rate - range",
    ],
    "Property type wise  Price per Sq. Ft. range wise unit sold": [
        "office - rate range unit sold",
        "shop - rate range unit sold",
        "flat - rate range unit sold",
        "others - rate range unit sold",
    ],
    "Property type wise total price range wise unit sold": [
        "flat - agreement price range unit sold",
        "others - agreement price range unit sold",
        "office - agreement price range unit sold",
        "shop - agreement price range unit sold",
    ],
    "BHK type wise  Price per Sq. Ft. range wise unit sold": [
        "1.5bhk - rate range unit sold",
        "1bhk - rate range unit sold",
        "2.5bhk - rate range unit sold",
        "2bhk - rate range unit sold",
        "3bhk - rate range unit sold",
        "<1bhk - rate range unit sold",
        ">3bhk - rate range unit sold",
        "2.25bhk - rate range unit sold",
        "2.75bhk - rate range unit sold",
    ],
    "total sales - as per premanual data": [
        "total_sales - premamnual",
    ],
    "total sales in developement agreement (DA)": [
        "total sales",
    ],
    "Property Type wise Total Sales (Agreement Price) as per premanual": [
        "apartment_sales - premamnual",
        "bunglow_sales - premamnual",
        "chawl_sales - premamnual",
        "flat_sales - premamnual",
        "commercial_sales - premamnual",
        "flat/shop_sales - premamnual",
        "not available_sales - premamnual",
        "office_sales - premamnual",
        "room_sales - premamnual",
        "row_house_sales - premamnual",
        "shop_sales - premamnual",
        "warehouse_sales - premamnual",
    ],
    "BHK wise total price range wise Units sold": [
        "1.5bhk - agreement price range unit sold",
        "1bhk - agreement price range unit sold",
        "2.5bhk - agreement price range unit sold",
        "2bhk - agreement price range unit sold",
        "3bhk - agreement price range unit sold",
        "<1bhk - agreement price range unit sold",
        ">3bhk - agreement price range unit sold",
        "2.25bhk - agreement price range unit sold",
        "2.75bhk - agreement price range unit sold",
    ],
    "Property type wise  Price per Sq. Ft. range wise total sales (INR)": [
        "flat - rate range total sales",
        "others - rate range total sales",
        "office - rate range total sales",
        "shop - rate range total sales",
    ],
    "Property type wise total price range wise Total Sales(INR)": [
        "others - agreement price range total sales",
        "flat - agreement price range total sales",
        "office - agreement price range total sales",
        "shop - agreement price range total sales",
    ],
    "BHK type wise  Price per Sq. Ft. range wise total sales (INR)": [
        "1.5bhk - rate range total sales",
        "1bhk - rate range total sales",
        "2.5bhk - rate range total sales",
        "2bhk - rate range total sales",
        "3bhk - rate range total sales",
        "<1bhk - rate range total sales",
        ">3bhk - rate range total sales",
        "2.25bhk - rate range total sales",
        "2.75bhk - rate range total sales",
    ],
    "BHK type wise total Price range wise total sales (INR)": [
        "1.5bhk - agreement price range total sales",
        "1bhk - agreement price range total sales",
        "2.5bhk - agreement price range total sales",
        "2bhk - rate range total sales",
        "3bhk - agreement price range total sales",
        "<1bhk - agreement price range total sales",
        ">3bhk - agreement price range total sales",
        "2.25bhk - agreement price range total sales",
        "2.75bhk - agreement price range total sales",
    ],
    "Property type wise  Price per Sq. Ft. range wise Carpet area sold or consumed": [
        "others - rate range carpet area consumed in sqft",
        "flat - rate range carpet area consumed in sqft",
        "office - rate range carpet area consumed in sqft",
        "shop - rate range carpet area consumed in sqft",
    ],
    "Agreement price wise range Carpet area consumed": [
        "others - agreement price range carpet area consumed in sqft",
        "flat - agreement price range carpet area consumed in sqft",
        "office - agreement price range carpet area consumed in sqft",
        "shop - agreement price range carpet area consumed in sqft",
    ],
    "BHK wise rate range wise carpet area consumed": [
        "1bhk - rate range carpet area consumed in sqft",
        "2bhk - rate range carpet area consumed in sqft",
        "3bhk - rate range carpet area consumed in sqft",
        "<1bhk - rate range carpet area consumed in sqft",
        ">3bhk - rate range carpet area consumed in sqft",
        "1.5bhk - rate range carpet area consumed in sqft",
        "2.5bhk - rate range carpet area consumed in sqft",
        "2.25bhk - rate range carpet area consumed in sqft",
        "2.75bhk - rate range carpet area consumed in sqft",
    ],
    "total carpet area consumed sqft according to RERA": [
        "total carpet area consumed (sqft) - rera",
    ],
    "Property Type wise Carpet area consumed/absorbed in Sq ft as per rera": [
        "office_carpet_area_consumed_rera_sqft",
        "others_carpet_area_consumed_rera_sqft",
        "shop_carpet_area_consumed_rera_sqft",
        "flat_carpet_area_consumed_rera_sqft",
    ],
    "BHK wise carpet area consumed in sqft according to RERA": [
        "<1bhk_carpet_area_consumed_rera_sqft",
        "1bhk_carpet_area_consumed_rera_sqft",
        "1.5bhk_carpet_area_consumed_rera_sqft",
        "2bhk_carpet_area_consumed_rera_sqft",
        "2.25bhk_carpet_area_consumed_rera_sqft",
        "2.5bhk_carpet_area_consumed_rera_sqft",
        "2.75bhk_carpet_area_consumed_rera_sqft",
        "3bhk_carpet_area_consumed_rera_sqft",
        ">3bhk_carpet_area_consumed_rera_sqft",
    ],
    "bhk wise Agreement price  range wise Carpet area consumed": [
        "1bhk - agreement price range carpet area consumed in sqft",
        "2bhk - agreement price range carpet area consumed in sqft",
        "3bhk - agreement price range carpet area consumed in sqft",
        "<1bhk - agreement price range carpet area consumed in sqft",
        ">3bhk - agreement price range carpet area consumed in sqft",
        "1.5bhk - agreement price range carpet area consumed in sqft",
        "2.5bhk - agreement price range carpet area consumed in sqft",
        "2.25bhk - agreement price range carpet area consumed in sqft",
        "2.75bhk - agreement price range carpet area consumed in sqft",
    ],
    "total units": [
        "total units",
    ],
    "Property Type wise total units": [
        "flat total",
        "shop total",
        "office total",
        "others total",
    ],
    "BHK wise total units": [
        "<1bhk total",
        "1bhk total",
        "1.5bhk total",
        "2bhk total",
        "2.25bhk total",
        "2.5bhk total",
        "2.75bhk total",
        "3bhk total",
        ">3bhk total",
    ],
    "Total Carpet Area (In sq ft)": [
        "total carpet area supplied (sqft)",
    ],
    "Property type wise Total Carpet Area (in sq ft)": [
        "flat_carpet_area_supplied_rera_sqft",
        "shop_carpet_area_supplied_rera_sqft",
        "others_carpet_area_supplied_rera_sqft",
        "office_carpet_area_supplied_rera_sqft",
        "undefined flats_carpet_area_supplied_rera_sqft",
    ],
    "BHK wise total carpet area in sqft": [
        "<1bhk_carpet_area_supplied_rera_sqft",
        "1bhk_carpet_area_supplied_rera_sqft",
        "1.5bhk_carpet_area_supplied_rera_sqft",
        "2bhk_carpet_area_supplied_rera_sqft",
        "2.25bhk_carpet_area_supplied_rera_sqft",
        "2.5bhk_carpet_area_supplied_rera_sqft",
        "2.75bhk_carpet_area_supplied_rera_sqft",
        "3bhk_carpet_area_supplied_rera_sqft",
        ">3bhk_carpet_area_supplied_rera_sqft",
        "undefined flats_carpet_area_supplied_rera_sqft",
    ],
    "Most prevailing rate for DA": [
        "rate_range_per_sqft",
    ],
    "total fsi supplied according to RERA": [
        "total fsi(sqft)",
    ],
    "total plot area in sqmtr according to RERA": [
        "plot area (sqmtr)",
    ],
    "Projects under construction as of the current date": [
        "u/c projects",
    ],
    "Completed Projects as of the current date": [
        "completed projects",
    ],
    "Project-Phases under construction as of the current date": [
        "u/c rera entries",
    ],
    "Completed Project-phases as of the current date": [
        "completed rera entries",
    ],
    "Total number of unique developers.": [
        "total no. of unique developers",
    ],
    "Date up to which village data is available in the premanual.": [
        "date till",
    ],
    "Development agreement": [
        "no. of d.a. registered",
        "total area conveyed for developement",
    ],
    "Total months to sell the unsold inventory.": [
        "months inventory",
    ],
    "Miscellaneous": [
        "city",
        "year",
        "total_sales",
        "max_floor",
        "regions",
        "average floor count",
        "completion count by project",
        "rera projects present in cgdb",
        "recent_transaction_date",
        "sold units in 2023",
        "sold units in 2024",
        "consumed area in 2023",
        "consumed area in 2024",
        "average units sold per month",
        "average carpet area consumed per month",
    ],
}

CATEGORY_MAPPING_Location = {
    "all": [
        "Location",
        "Total Buildings or Towers",
        "Total Phases Launched",
        "Total Project Launched",
        "Total property type wise projects",
        "broad property types Share (%)",
    ],
    "demand": [
        "BHK types wise units sold",
        "BHK wise Average Carpet Area in sqft",
        "BHK wise Carpet Area  sold or consumed in sqft",
        "BHK wise Carpet Area range wise Units sold",
        "BHK wise Carpet area range wise Total sales(INR)",
        "BHK wise carpet area range wise carpet area  sold or consumed in sqft",
        "Development agreement",
        "Property Type wise Carpet area sold or consumed in sqft",
        "Property type wise Average Carpet Area in sqft",
        "Property type wise Carpet Area range wise Units sold",
        "Property type wise Carpet area range wise Total sales (INR)",
        "Property type wise Units Sold",
        "Property type wise carpet area range wise Carpet area  sold or consumed in sqft",
        "Total Carpet Area sold or consumed in sqft",
        "Total units sold",
        "broad  Property Type wise Carpet area  sold or consumed in sqft",
        "broad property types wise unit sold",
    ],
    "demography": [
        "BHK wise Age Range wise Carpet Area  sold or consumed in sqft",
        "BHK wise Age Range wise Total sales (INR)",
        "BHK wise Age Range wise units sold",
        "BHK wise Top 10 Buyer Pincode",
        "BHK wise Top 10 Buyer Pincode wise Carpet Area  sold or consumed in sqft",
        "BHK wise Top 10 Buyer Pincode wise Total sales (INR)",
        "Property type wise Age Range wise Carpet Area  sold or consumed in sqft",
        "Property type wise Age Range wise Total sales (INR)",
        "Property type wise Age Range wise unit sold",
        "Property type wise Top 10 Buyer Pincode",
        "Property type wise Top 10 Buyer Pincode wise Carpet Area sold or consumed in sqft",
        "Property type wise Top 10 Buyer Pincode wise Total sales (INR)",
        "Top 10 Buyer Pincode units sold",
        "Top buyer pincode",
    ],
    "price": [
        "Agreement price wise range Carpet area consumed",
        "BHK type wise  Price per Sq. Ft. range wise total sales (INR)",
        "BHK type wise  Price per Sq. Ft. range wise unit sold",
        "BHK type wise total Price range wise total sales (INR)",
        "BHK wise Average Price (INR)",
        "BHK wise Total Sales (INR)",
        "BHK wise rate range wise carpet area consumed",
        "BHK wise total price range wise Units sold",
        "Broad Property category wise Total sales (INR)",
        "Most prevailing rate for DA",
        "Property Type Wise Average Price per Sq. Ft. (Carpet Area Basis)",
        "Property Type Wise Percentile's Price per Sq. Ft. (Carpet Area Basis)",
        "Property Type wise Average Price (INR)",
        "Property Type wise Most Prevailing Price per Sq.Ft. Range (Rupees per sq foot)",
        "Property Type wise Total Sales (INR)",
        "Property category wise Average Price (INR)",
        "Property type wise  Price per Sq. Ft. range wise Carpet area sold or consumed",
        "Property type wise  Price per Sq. Ft. range wise total sales (INR)",
        "Property type wise  Price per Sq. Ft. range wise unit sold",
        "Property type wise total price range wise Total Sales(INR)",
        "Property type wise total price range wise unit sold",
        "Total sales (INR)",
        "bhk wise Agreement price  range wise Carpet area consumed",
        "total sales in developement agreement (DA)",
    ],
    "supply": [
        "BHK wise total carpet area in sqft",
        "BHK wise total units",
        "Property Type wise total units",
        "Property type wise Total Carpet Area (in sq ft)",
        "Total Carpet Area (In sq ft)",
        "total units",
    ],
}


COLUMN_MAPPING_Project = {
    "Project Name": [
        "project name",
    ],
    "Project Location": [
        "final_location",
    ],
    "Project City": [
        "city",
    ],
    "Type of Project": [
        "project type",
    ],
    "Project commencement date": [
        "commencement date",
    ],
    "Project Completion date": [
        "completion date",
    ],
    "broad property types Share (%)": [
        "residential share (in %)",
        "commercial share (in %)",
        "others share (in %)",
    ],
    "total floors": [
        "min no sac floor",
        "max no sac floor",
    ],
    "Project coordinates (Latitude- lat, Longitude- lng)": [
        "project_lat",
        "project_lng",
    ],
    "Total Phases of Project": [
        "project name (with rera entry)",
    ],
    "Name of the organization/ Indvidual": [
        "organization/individual",
    ],
    "No of Buildings or Towers in Project": [
        "rera entry count",
        "total block count",
    ],
    "Units sold": [
        "adopted sold",
    ],
    "Property Type wise Unit Sold": [
        "flat adopted sold",
        "shop adopted sold",
        "office adopted sold",
        "others adopted sold",
    ],
    "BHK Type wise Unit Sold": [
        "<1bhk adopted sold",
        "1bhk adopted sold",
        "1.5bhk adopted sold",
        "2bhk adopted sold",
        "2.25bhk adopted sold",
        "2.5bhk adopted sold",
        "2.75bhk adopted sold",
        "3bhk adopted sold",
        ">3bhk adopted sold",
    ],
    "Property type wise carpet area range wise unit sold": [
        "flat - total_sold_area_range_info",
        "office - total_sold_area_range_info",
        "others - total_sold_area_range_info",
        "shop - total_sold_area_range_info",
    ],
    "Property type wise carpet area range wise total sales (INR)": [
        "flat- total agreement price in area range",
        "office- total agreement price in area range",
        "others- total agreement price in area range",
        "shop- total agreement price in area range",
    ],
    "Bhk type wise carpet area range wise unit sold": [
        "1.5bhk - total_sold_area_range_info",
        "1bhk - total_sold_area_range_info",
        "2.25bhk - total_sold_area_range_info",
        "2.5bhk - total_sold_area_range_info",
        "2.75bhk - total_sold_area_range_info",
        "2bhk - total_sold_area_range_info",
        "3bhk - total_sold_area_range_info",
        "<1bhk - total_sold_area_range_info",
        ">3bhk - total_sold_area_range_info",
    ],
    "Bhk type wise carpet area range wise total sales (INR)": [
        "1.5bhk- total agreement price in area range",
        "1bhk- total agreement price in area range",
        "2.25bhk- total agreement price in area range",
        "2.5bhk- total agreement price in area range",
        "2.75bhk- total agreement price in area range",
        "2bhk- total agreement price in area range",
        "3bhk- total agreement price in area range",
        "<1bhk- total agreement price in area range",
        ">3bhk- total agreement price in area range",
    ],
    "Bhk type wise carpet area range wise average price (INR)": [
        "1.5bhk- avg agreement price in area range",
        "1bhk- avg agreement price in area range",
        "2.25bhk- avg agreement price in area range",
        "2.5bhk- avg agreement price in area range",
        "2.75bhk- avg agreement price in area range",
        "2bhk- avg agreement price in area range",
        "3bhk- avg agreement price in area range",
        "<1bhk- avg agreement price in area range",
        ">3bhk- avg agreement price in area range",
    ],
    "BHK type wise average carpet area in sqft": [
        "1.5bhk - avg carpet area (in sqft)",
        "1bhk - avg carpet area (in sqft)",
        "2.25bhk - avg carpet area (in sqft)",
        "2.5bhk - avg carpet area (in sqft)",
        "2.75bhk - avg carpet area (in sqft)",
        "2bhk - avg carpet area (in sqft)",
        "3bhk - avg carpet area (in sqft)",
        "<1bhk - avg carpet area (in sqft)",
        ">3bhk - avg carpet area (in sqft)",
    ],
    "Property type wise average carpet area in sqft": [
        "office - avg carpet area (in sqft)",
        "others - avg carpet area (in sqft)",
        "shop - avg carpet area (in sqft)",
    ],
    "Top Buyer Pincode": [
        "top_buyer_pincode",
    ],
    "Top 10 Buyer Pincode": [
        "top10_project_buyer",
    ],
    "Total sales (INR)": [
        "total_sales",
    ],
    "Property Type wise Total Sales (INR)": [
        "flat- total agreement price",
        "office- total agreement price",
        "others- total agreement price",
        "shop- total agreement price",
    ],
    "Property Type wise Average Price (INR)": [
        "flat- avg agreement price",
        "office- avg agreement price",
        "others- avg agreement price",
        "shop- avg agreement price",
    ],
    "BHK type wise Total Sales (INR)": [
        "1.5bhk- total agreement price",
        "1bhk- total agreement price",
        "2.25bhk- total agreement price",
        "2.5bhk- total agreement price",
        "2.75bhk- total agreement price",
        "2bhk- total agreement price",
        "3bhk- total agreement price",
        "<1bhk- total agreement price",
        ">3bhk- total agreement price",
    ],
    "BHK type wise Average Price (INR)": [
        "1.5bhk- avg agreement price",
        "1bhk- avg agreement price",
        "2.25bhk- avg agreement price",
        "2.5bhk- avg agreement price",
        "2.75bhk- avg agreement price",
        "2bhk- avg agreement price",
        "3bhk- avg agreement price",
        "<1bhk- avg agreement price",
        ">3bhk- avg agreement price",
    ],
    "Property Type Wise Average Price per Sq. Ft. (Carpet Area Basis)": [
        "flat - weighted average rate",
        "office - weighted average rate",
        "others - weighted average rate",
        "shop - weighted average rate",
    ],
    "Property Type wise Most Prevailing Price per Sq.Ft. Range (Rupees per sq foot)": [
        "flat - most prevailing rate - range",
        "office - most prevailing rate - range",
        "others - most prevailing rate - range",
        "shop - most prevailing rate - range",
    ],
    "BHK Type Wise Average Price per Sq. Ft. (Carpet Area Basis)": [
        "1.5Bhk - Weighted Average Rate",
        "1Bhk - Weighted Average Rate",
        "2.25Bhk - Weighted Average Rate",
        "2.5Bhk - Weighted Average Rate",
        "2.75Bhk - Weighted Average Rate",
        "2Bhk - Weighted Average Rate",
        "3Bhk - Weighted Average Rate",
        "<1Bhk - Weighted Average Rate",
        ">3Bhk - Weighted Average Rate",
    ],
    "Property type wise total price range wise unit sold": [
        "flat - agreement price range unit sold",
        "shop - agreement price range unit sold",
        "others - agreement price range unit sold",
        "office - agreement price range unit sold",
    ],
    "Property type wise total price range wise Total Sales(INR)": [
        "flat - agreement price range total sales",
        "shop - agreement price range total sales",
        "others - agreement price range total sales",
        "office - agreement price range total sales",
    ],
    "Property type wise total price  range wise Carpet area sold or consumed": [
        "flat - agreement price range carpet area consumed in sqft",
        "shop - agreement price range carpet area consumed in sqft",
        "others - agreement price range carpet area consumed in sqft",
        "office - agreement price range carpet area consumed in sqft",
    ],
    "BHK type wise total price range wise unit sold": [
        "1bhk - agreement price range unit sold",
        "2bhk - agreement price range unit sold",
        "3bhk - agreement price range unit sold",
        ">3bhk - agreement price range unit sold",
        "<1bhk - agreement price range unit sold",
        "1.5bhk - agreement price range unit sold",
        "2.5bhk - agreement price range unit sold",
        "2.25bhk - agreement price range unit sold",
        "2.75bhk - agreement price range unit sold",
    ],
    "BHK type wise total price range wise Total Sales(INR)": [
        "1bhk - agreement price range total sales",
        "2bhk - agreement price range total sales",
        "3bhk - agreement price range total sales",
        ">3bhk - agreement price range total sales",
        "<1bhk - agreement price range total sales",
        "1.5bhk - agreement price range total sales",
        "2.5bhk - agreement price range total sales",
        "2.25bhk - agreement price range total sales",
        "2.75bhk - agreement price range total sales",
    ],
    "Bhk type wise total price  range wise Carpet area sold or consumed": [
        "1bhk - agreement price range carpet area consumed in sqft",
        "2bhk - agreement price range carpet area consumed in sqft",
        "3bhk - agreement price range carpet area consumed in sqft",
        ">3bhk - agreement price range carpet area consumed in sqft",
        "<1bhk - agreement price range carpet area consumed in sqft",
        "1.5bhk - agreement price range carpet area consumed in sqft",
        "2.5bhk - agreement price range carpet area consumed in sqft",
        "2.25bhk - agreement price range carpet area consumed in sqft",
        "2.75bhk - agreement price range carpet area consumed in sqft",
    ],
    "Property type wise  Price per Sq. Ft. range wise unit sold": [
        "flat - total_sold_rate_range_info",
        "office - total_sold_rate_range_info",
        "others - total_sold_rate_range_info",
        "shop - total_sold_rate_range_info",
    ],
    "Total Units in Project": [
        "total units",
    ],
    "Total Carpet Area in Sqmtr": [
        "total carpet area supplied (sqmtr)",
    ],
    "Property Type wise Total Units": [
        "flat total",
        "shop total",
        "office total",
        "others total",
    ],
    "BHK Type wise Total Units": [
        "<1bhk total",
        "1bhk total",
        "1.5bhk total",
        "2bhk total",
        "2.25bhk total",
        "2.5bhk total",
        "2.75bhk total",
        "3bhk total",
        ">3bhk total",
        "undefined flats total",
    ],
    "BHK Type wise Total Carpet area in Sqmtr": [
        "1.5bhk_carpet_area_supplied_rera",
        "1bhk_carpet_area_supplied_rera",
        "<1bhk_carpet_area_supplied_rera",
        "2.25bhk_carpet_area_supplied_rera",
        "2.5bhk_carpet_area_supplied_rera",
        "2.75bhk_carpet_area_supplied_rera",
        "2bhk_carpet_area_supplied_rera",
        ">3bhk_carpet_area_supplied_rera",
        "3bhk_carpet_area_supplied_rera",
        "undefined flats_carpet_area_supplied_rera",
    ],
    "Property Type wise Total Carpet area supplied in Sqmtr": [
        "office_carpet_area_supplied_rera",
        "others_carpet_area_supplied_rera",
        "shop_carpet_area_supplied_rera",
        "flat_carpet_area_supplied_rera",
    ],
    "Property type and BHK type wise carpet area range in sqmtr": [
        "1bhk ca range (in sqmt.)",
        "1.5bhk ca range (in sqmt.)",
        "2bhk ca range (in sqmt.)",
        "2.25bhk ca range (in sqmt.)",
        "2.5bhk ca range (in sqmt.)",
        "2.75bhk ca range (in sqmt.)",
        "3bhk ca range (in sqmt.)",
        ">3bhk ca range (in sqmt.)",
        "undefined flats ca range (in sqmt.)",
        "shop ca range (in sqmt.)",
        "office ca range (in sqmt.)",
        "others ca range (in sqmt.)",
    ],
    "Projects Adopted Unsold units": [
        "adopted unsold",
    ],
    "Property type wise unsold units": [
        "flat adopted unsold",
        "shop adopted unsold",
        "office adopted unsold",
        "others adopted unsold",
    ],
    "Total FSI in Project in Sqmtr": [
        "total fsi (sqmtr)",
        "plot area (sqmtr)"
    ],
    "BHK type wise unsold units": [
        "<1bhk adopted unsold",
        "1bhk adopted unsold",
        "1.5bhk adopted unsold",
        "2bhk adopted unsold",
        "2.25bhk adopted unsold",
        "2.5bhk adopted unsold",
        "2.75bhk adopted unsold",
        "3bhk adopted unsold",
        ">3bhk adopted unsold",
    ],
}

CATEGORY_MAPPING_Project = {
    "all": [
        "Name of the organization/ Indvidual",
        "No of Buildings or Towers in Project",
        "Project City",
        "Project Completion date",
        "Project Location",
        "Project Name",
        "Project commencement date",
        "Project coordinates (Latitude- lat, Longitude- lng)",
        "Total Phases of Project",
        "Type of Project",
        "broad property types Share (%)",
        "total floors",
    ],
    "demand": [
        "BHK Type wise Carpet area sold or consumed in sqft",
        "BHK Type wise Unit Sold",
        "BHK type wise average carpet area in sqft",
        "Bhk type wise carpet area range wise average price (INR)",
        "Bhk type wise carpet area range wise total sales (INR)",
        "Bhk type wise carpet area range wise unit sold",
        "Property Type wise Carpet area sold or consumed in Sqft",
        "Property Type wise Unit Sold",
        "Property type wise average carpet area in sqft",
        "Property type wise carpet area range wise total sales (INR)",
        "Property type wise carpet area range wise unit sold",
        "Total Carpet Area sold or consumed in sqmtr",
        "Units sold",
    ],
    "demography": [
        "Top 10 Buyer Pincode",
        "Top Buyer Pincode",
    ],
    "price": [
        "BHK Type Wise Average Price per Sq. Ft. (Carpet Area Basis)",
        "BHK type wise Average Price (INR)",
        "BHK type wise Total Sales (INR)",
        "BHK type wise total price range wise Total Sales(INR)",
        "BHK type wise total price range wise unit sold",
        "Bhk type wise total price  range wise Carpet area sold or consumed",
        "Property Type Wise Average Price per Sq. Ft. (Carpet Area Basis)",
        "Property Type Wise Percentile's Price per Sq. Ft. (Carpet Area Basis)",
        "Property Type wise Average Price (INR)",
        "Property Type wise Current Rate (Rupees per sq foot)",
        "Property Type wise Most Prevailing Price per Sq.Ft. Range (Rupees per sq foot)",
        "Property Type wise Total Sales (INR)",
        "Property type wise  Price per Sq. Ft. range wise unit sold",
        "Property type wise total price  range wise Carpet area sold or consumed",
        "Property type wise total price range wise Total Sales(INR)",
        "Property type wise total price range wise unit sold",
        "Total sales (INR)",
    ],
    "supply": [
        "BHK Type wise Total Carpet area in Sqmtr",
        "BHK Type wise Total Units",
        "Project Crapet area range in sqmtr",
        "Property Type wise Total Carpet area supplied in Sqmtr",
        "Property Type wise Total Units",
        "Property type and BHK type wise carpet area range in sqmtr",
        "Total Carpet Area in Sqmtr",
        "Total FSI in Project in Sqmtr",
        "Total Units in Project",
    ],
    "unsold": [
        "BHK type wise unsold units",
        "Projects Adopted Unsold units",
        "Property type wise unsold units",
    ],
}


COLUMN_MAPPING_City = {
    "Name of the City": [
        "city",
    ],
    "Total Project Launched": [
        "total projects commenced",
    ],
    "Total Completed Project": [
        "completion count by project",
    ],
    "Total Phases Launched": [
        "rera entry wise commenced count",
    ],
    "Total Completed Phases": [
        "rera entry wise completion count",
    ],
    "Total Buildings or Towers": [
        "total no. of blocks (based of projects)",
    ],
    "Total property type wise projects": [
        "no. of commercial projects",
        "no. of others projects",
        "no. of residential projects",
        "residential+commercial",
        "no. of indusrial projects",
    ],
    "Carpet area sold or consumed": [
        "total carpet area consumed (sqft) - igr",
    ],
    "Units Sold": [
        "total sold - igr",
    ],
    "Property type wise unit sold": [
        "flat_sold - igr",
        "office_sold - igr",
        "others_sold - igr",
        "shop_sold - igr",
    ],
    "Property type wise Carpet area sold or consumed": [
        "flat_carpet_area_consumed(in sqft) - igr",
        "office_carpet_area_consumed(in sqft) - igr",
        "others_carpet_area_consumed(in sqft) - igr",
        "shop_carpet_area_consumed(in sqft) - igr",
    ],
    "BHK type wise unit sold": [
        "1.5bhk_sold - igr",
        "1bhk_sold - igr",
        "2.25bhk_sold - igr",
        "2.5bhk_sold - igr",
        "2.75bhk_sold - igr",
        "2bhk_sold - igr",
        "3bhk_sold - igr",
        "<1bhk_sold - igr",
        ">3bhk_sold - igr",
    ],
    "BHK type wise Carpet area sold or consumed": [
        "1.5bhk_carpet_area_consumed(in sqft) - igr",
        "1bhk_carpet_area_consumed(in sqft) - igr",
        "2.25bhk_carpet_area_consumed(in sqft) - igr",
        "2.5bhk_carpet_area_consumed(in sqft) - igr",
        "2.75bhk_carpet_area_consumed(in sqft) - igr",
        "2bhk_carpet_area_consumed(in sqft) - igr",
        "3bhk_carpet_area_consumed(in sqft) - igr",
        "<1bhk_carpet_area_consumed(in sqft) - igr",
        ">3bhk_carpet_area_consumed(in sqft) - igr",
    ],
    "broad property types wise unit sold": [
        "commercial_sold - igr",
        "other_sold - igr",
        "residential_sold - igr",
    ],
    "broad property type wise Carpet area sold or consumed": [
        "commercial_carpet_area_consumed(in sqft) - igr",
        "other_carpet_area_consumed(in sqft) - igr",
        "residential_carpet_area_consumed(in sqft) - igr",
    ],
    "Property type wise area range wise unit sold": [
        "flat - area range unit sold",
        "office - area range unit sold",
        "others - area range unit sold",
        "shop - area range unit sold",
    ],
    "Property type wise area range wise total sales analysis (INR)": [
        "flat - area range total sales",
        "office - area range total sales",
        "others - area range total sales",
        "shop - area range total sales",
    ],
    "Property type wise area range wise Carpet area sold or consumed": [
        "flat - area range carpet area consumed in sqft",
        "office - area range carpet area consumed in sqft",
        "others - area range carpet area consumed in sqft",
        "shop - area range carpet area consumed in sqft",
    ],
    "BHK type wise area range wise unit sold": [
        "1.5bhk - area range unit sold",
        "1bhk - area range unit sold",
        "2.5bhk - area range unit sold",
        "2bhk - area range unit sold",
        "3bhk - area range unit sold",
        "<1bhk - area range unit sold",
        ">3bhk - area range unit sold",
        "2.25bhk - area range unit sold",
        "2.75bhk - area range unit sold",
    ],
    "BHK type wise area range wise total sales analysis (INR)": [
        "1.5bhk - area range total sales",
        "1bhk - area range total sales",
        "2.5bhk - area range total sales",
        "2bhk - area range total sales",
        "3bhk - area range total sales",
        "<1bhk - area range total sales",
        ">3bhk - area range total sales",
        "2.25bhk - area range total sales",
        "2.75bhk - area range total sales",
    ],
    "BHK type wise area range wise Carpet area sold or consumed": [
        "1.5bhk - area range carpet area consumed in sqft",
        "1bhk - area range carpet area consumed in sqft",
        "2.5bhk - area range carpet area consumed in sqft",
        "2bhk - area range carpet area consumed in sqft",
        "3bhk - area range carpet area consumed in sqft",
        "<1bhk - area range carpet area consumed in sqft",
        ">3bhk - area range carpet area consumed in sqft",
        "2.25bhk - area range carpet area consumed in sqft",
        "2.75bhk - area range carpet area consumed in sqft",
    ],
    "Top buyer pincode": [
        "top_buyer_pincode",
    ],
    "Top 10 Buyer Pincode": [
        "top10_buyer_in_locality",
    ],
    "Property type wise top buuyers pincode wise unit sold": [
        "flat - pincode wise unit sold",
        "office - pincode wise unit sold",
        "others - pincode wise unit sold",
        "shop - pincode wise unit sold",
    ],
    "Property type wise top buuyers pincode wise total sales (INR)": [
        "flat - pincode wise total sales",
        "office - pincode wise total sales",
        "others - pincode wise total sales",
        "shop - pincode wise total sales",
    ],
    "Property type wise top buuyers pincode wise Carpet area sold or consumed": [
        "flat - pincode wise carpet area consumed in sqft",
        "office - pincode wise carpet area consumed in sqft",
        "others - pincode wise carpet area consumed in sqft",
        "shop - pincode wise carpet area consumed in sqft",
    ],
    "BHK type wise top buuyers pincode wise unit sold": [
        "1.5bhk - pincode wise unit sold",
        "1bhk - pincode wise unit sold",
        "2.5bhk - pincode wise unit sold",
        "2bhk - pincode wise unit sold",
        "3bhk - pincode wise unit sold",
        "<1bhk - pincode wise unit sold",
        ">3bhk - pincode wise unit sold",
        "2.25bhk - pincode wise unit sold",
        "2.75bhk - pincode wise unit sold",
    ],
    "BHK type wise top buuyers pincode wise total sales (INR)": [
        "1.5bhk - pincode wise total sales",
        "1bhk - pincode wise total sales",
        "2.5bhk - pincode wise total sales",
        "2bhk - pincode wise total sales",
        "3bhk - pincode wise total sales",
        "<1bhk - pincode wise total sales",
        ">3bhk - pincode wise total sales",
        "2.25bhk - pincode wise total sales",
        "2.75bhk - pincode wise total sales",
    ],
    "BHK type wise top buuyers pincode wise Carpet area sold or consumed": [
        "1.5bhk - pincode wise carpet area consumed in sqft",
        "1bhk - pincode wise carpet area consumed in sqft",
        "2.5bhk - pincode wise carpet area consumed in sqft",
        "2bhk - pincode wise carpet area consumed in sqft",
        "3bhk - pincode wise carpet area consumed in sqft",
        "<1bhk - pincode wise carpet area consumed in sqft",
        ">3bhk - pincode wise carpet area consumed in sqft",
        "2.25bhk - pincode wise carpet area consumed in sqft",
        "2.75bhk - pincode wise carpet area consumed in sqft",
    ],
    "Property type wise Age Range wise units sold": [
        "flat - age range wise unit sold",
        "office - age range wise unit sold",
        "others - age range wise unit sold",
        "shop - age range wise unit sold",
    ],
    "Property type wise Age Range wise total sales (INR)": [
        "flat - age range wise total sales",
        "office - age range wise total sales",
        "others - age range wise total sales",
        "shop - age range wise total sales",
    ],
    "Property type wise Age Range wise carpet area sold or consumed": [
        "flat - age range wise carpet area consumed in sqft",
        "office - age range wise carpet area consumed in sqft",
        "others - age range wise carpet area consumed in sqft",
        "shop - age range wise carpet area consumed in sqft",
    ],
    "BHK type wise Age Range wise units sold": [
        "1.5bhk - age range wise unit sold",
        "1bhk - age range wise unit sold",
        "2.5bhk - age range wise unit sold",
        "2bhk - age range wise unit sold",
        "3bhk - age range wise unit sold",
        "<1bhk - age range wise unit sold",
        ">3bhk - age range wise unit sold",
        "2.25bhk - age range wise unit sold",
        "2.75bhk - age range wise unit sold",
    ],
    "BHK type wise Age Range wise total sales (INR)": [
        "1.5bhk - age range wise total sales",
        "1bhk - age range wise total sales",
        "2.5bhk - age range wise total sales",
        "2bhk - age range wise total sales",
        "3bhk - age range wise total sales",
        "<1bhk - age range wise total sales",
        ">3bhk - age range wise total sales",
        "2.25bhk - age range wise total sales",
        "2.75bhk - age range wise total sales",
    ],
    "BHK type wise Age Range wise carpet area sold or consumed": [
        "1.5bhk - age range wise carpet area consumed in sqft",
        "1bhk - age range wise carpet area consumed in sqft",
        "2.5bhk - age range wise carpet area consumed in sqft",
        "2bhk - age range wise carpet area consumed in sqft",
        "3bhk - age range wise carpet area consumed in sqft",
        "<1bhk - age range wise carpet area consumed in sqft",
        ">3bhk - age range wise carpet area consumed in sqft",
        "2.25bhk - age range wise carpet area consumed in sqft",
        "2.75bhk - age range wise carpet area consumed in sqft",
    ],
    "Property type wise average carpet area": [
        "flat - avg carpet area (in sqft)",
        "office - avg carpet area (in sqft)",
        "others - avg carpet area (in sqft)",
        "shop - avg carpet area (in sqft)",
    ],
    "BHK type wise average carpet area": [
        "1.5bhk - avg carpet area (in sqft)",
        "1bhk - avg carpet area (in sqft)",
        "2.25bhk - avg carpet area (in sqft)",
        "2.5bhk - avg carpet area (in sqft)",
        "2.75bhk - avg carpet area (in sqft)",
        "2bhk - avg carpet area (in sqft)",
        "3bhk - avg carpet area (in sqft)",
        "<1bhk - avg carpet area (in sqft)",
        ">3bhk - avg carpet area (in sqft)",
    ],
    "Total sales (INR)": [
        "total_sales - igr",
    ],
    "Property type wise Total Sales (INR)": [
        "flat- total agreement price",
        "office- total agreement price",
        "others- total agreement price",
        "shop- total agreement price",
    ],
    "Property type wise Average Price (INR)": [
        "flat- avg agreement price",
        "office- avg agreement price",
        "others- avg agreement price",
        "shop- avg agreement price",
    ],
    "BHK wise Total sales (INR)": [
        "1.5bhk- total agreement price",
        "1bhk- total agreement price",
        "2.25bhk- total agreement price",
        "2.5bhk- total agreement price",
        "2.75bhk- total agreement price",
        "2bhk- total agreement price",
        "3bhk- total agreement price",
        "<1bhk- total agreement price",
        ">3bhk- total agreement price",
    ],
    "BHK wise average price (INR)": [
        "1.5bhk- avg agreement price",
        "1bhk- avg agreement price",
        "2.25bhk- avg agreement price",
        "2.5bhk- avg agreement price",
        "2.75bhk- avg agreement price",
        "2bhk- avg agreement price",
        "3bhk- avg agreement price",
        "<1bhk- avg agreement price",
        ">3bhk- avg agreement price",
    ],
    "broad property type wise total sales (INR)": [
        "commercial- total agreement price",
        "other- total agreement price",
        "residential- total agreement price",
    ],
    "broad property type wise average price (INR)": [
        "commercial- avg agreement price",
        "other- avg agreement price",
        "residential- avg agreement price",
    ],
    "Property Type Wise Average Price per Sq. Ft. (Carpet Area Basis)": [
        "flat - weighted average rate",
        "office - weighted average rate",
        "others - weighted average rate",
        "shop - weighted average rate",
    ],
    "Property Type Wise Percentile's Price per Sq. Ft. (Carpet Area Basis)": [
        "flat - 50th percentile rate",
        "office - 50th percentile rate",
        "others - 50th percentile rate",
        "shop - 50th percentile rate",
        "flat - 75th percentile rate",
        "office - 75th percentile rate",
        "others - 75th percentile rate",
        "shop - 75th percentile rate",
        "flat - 90th percentile rate",
        "office - 90th percentile rate",
        "others - 90th percentile rate",
        "shop - 90th percentile rate",
    ],
    "Property Type Wise most prevailing Price per Sq. Ft. (Carpet Area Basis)": [
        "flat - most prevailing rate - range",
        "office - most prevailing rate - range",
        "others - most prevailing rate - range",
        "shop - most prevailing rate - range",
    ],
    "Property type wise Price (/sqft) range wise Units sold": [
        "flat - rate range unit sold",
        "office - rate range unit sold",
        "others - rate range unit sold",
        "shop - rate range unit sold",
    ],
    "Property type wise Price (/sqft) range wise total sales (INR)": [
        "flat - rate range total sales",
        "office - rate range total sales",
        "others - rate range total sales",
        "shop - rate range total sales",
    ],
    "Property type wise Price (/sqft) range wise carpet area sold or consumed": [
        "flat - rate range carpet area consumed in sqft",
        "office - rate range carpet area consumed in sqft",
        "others - rate range carpet area consumed in sqft",
        "shop - rate range carpet area consumed in sqft",
    ],
    "Property type wise total price range wise unit sold": [
        "flat - agreement price range unit sold",
        "office - agreement price range unit sold",
        "others - agreement price range unit sold",
        "shop - agreement price range unit sold",
    ],
    "Property type wise total price range wise total sales (INR)": [
        "flat - agreement price range total sales",
        "office - agreement price range total sales",
        "others - agreement price range total sales",
        "shop - agreement price range total sales",
    ],
    "Property type wise total price range wise  carpet area sold or consumed": [
        "flat - agreement price range carpet area consumed in sqft",
        "office - agreement price range carpet area consumed in sqft",
        "others - agreement price range carpet area consumed in sqft",
        "shop - agreement price range carpet area consumed in sqft",
    ],
    "BHK type wise Price (/sqft) range wise Units sold": [
        "1.5bhk - rate range unit sold",
        "1bhk - rate range unit sold",
        "2.5bhk - rate range unit sold",
        "2bhk - rate range unit sold",
        "3bhk - rate range unit sold",
        "<1bhk - rate range unit sold",
        ">3bhk - rate range unit sold",
        "2.25bhk - rate range unit sold",
        "2.75bhk - rate range unit sold",
    ],
    "BHK type wise Price (/sqft) range wise total sales (INR)": [
        "1.5bhk - rate range total sales",
        "1bhk - rate range total sales",
        "2.5bhk - rate range total sales",
        "2bhk - rate range total sales",
        "3bhk - rate range total sales",
        "<1bhk - rate range total sales",
        ">3bhk - rate range total sales",
        "2.25bhk - rate range total sales",
        "2.75bhk - rate range total sales",
    ],
    "BHK type wise Price (/sqft) range wise carpet area sold or consumed": [
        "1.5bhk - rate range carpet area consumed in sqft",
        "1bhk - rate range carpet area consumed in sqft",
        "2.5bhk - rate range carpet area consumed in sqft",
        "2bhk - rate range carpet area consumed in sqft",
        "3bhk - rate range carpet area consumed in sqft",
        "<1bhk - rate range carpet area consumed in sqft",
        ">3bhk - rate range carpet area consumed in sqft",
        "2.25bhk - rate range carpet area consumed in sqft",
        "2.75bhk - rate range carpet area consumed in sqft",
    ],
    "BHK type wise total price range wise unit sold": [
        "1.5bhk - agreement price range unit sold",
        "1bhk - agreement price range unit sold",
        "2.5bhk - agreement price range unit sold",
        "2bhk - agreement price range unit sold",
        "3bhk - agreement price range unit sold",
        "<1bhk - agreement price range unit sold",
        ">3bhk - agreement price range unit sold",
        "2.25bhk - agreement price range unit sold",
        "2.75bhk - agreement price range unit sold",
    ],
    "BHK type wise total price range wise total sales (INR)": [
        "1.5bhk - agreement price range total sales",
        "1bhk - agreement price range total sales",
        "2.5bhk - agreement price range total sales",
        "2bhk - agreement price range total sales",
        "3bhk - agreement price range total sales",
        "<1bhk - agreement price range total sales",
        ">3bhk - agreement price range total sales",
        "2.25bhk - agreement price range total sales",
        "2.75bhk - agreement price range total sales",
    ],
    "BHK type wise total price range wise  carpet area sold or consumed": [
        "1.5bhk - agreement price range carpet area consumed in sqft",
        "1bhk - agreement price range carpet area consumed in sqft",
        "2.5bhk - agreement price range carpet area consumed in sqft",
        "2bhk - agreement price range carpet area consumed in sqft",
        "3bhk - agreement price range carpet area consumed in sqft",
        "<1bhk - agreement price range carpet area consumed in sqft",
        ">3bhk - agreement price range carpet area consumed in sqft",
        "2.25bhk - agreement price range carpet area consumed in sqft",
        "2.75bhk - agreement price range carpet area consumed in sqft",
    ],
    "Total Number of Units": [
        "total units",
    ],
    "Total Carpet Area": [
        "total carpet area supplied (sqft)",
    ],
    "Total FSI in Sqft": [
        "total fsi(sqft)",
    ],
    "Total Plot Area in Sqmtr": [
        "plot area (sqmtr)",
    ],
    "Property type wise total units": [
        "flat total",
        "shop total",
        "office total",
        "others total",
    ],
    "BHK type wise total units": [
        "1bhk total",
        "1.5bhk total",
        "2bhk total",
        "2.25bhk total",
        "2.5bhk total",
        "2.75bhk total",
        "3bhk total",
        ">3bhk total",
        "<1bhk total",
        "undefined flats total",
    ],
    "BHK type wise total carpet area": [
        "1.5bhk_carpet_area_supplied_rera_sqft",
        "1bhk_carpet_area_supplied_rera_sqft",
        "<1bhk_carpet_area_supplied_rera_sqft",
        "2.25bhk_carpet_area_supplied_rera_sqft",
        "2.5bhk_carpet_area_supplied_rera_sqft",
        "2.75bhk_carpet_area_supplied_rera_sqft",
        "2bhk_carpet_area_supplied_rera_sqft",
        ">3bhk_carpet_area_supplied_rera_sqft",
        "3bhk_carpet_area_supplied_rera_sqft",
    ],
    "Property type wise total carpet area": [
        "undefined flats_carpet_area_supplied_rera_sqft",
        "office_carpet_area_supplied_rera_sqft",
        "others_carpet_area_supplied_rera_sqft",
        "shop_carpet_area_supplied_rera_sqft",
        "flat_carpet_area_supplied_rera_sqft",
    ],
}


CATEGORY_MAPPING_City = {
    "all": [
        "Name of the City",
        "Total Buildings or Towers",
        "Total Completed Phases",
        "Total Completed Project",
        "Total Phases Launched",
        "Total Project Launched",
        "Total property type wise projects",
    ],
    "demand": [
        "BHK type wise Carpet area sold or consumed",
        "BHK type wise area range wise Carpet area sold or consumed",
        "BHK type wise area range wise total sales analysis (INR)",
        "BHK type wise area range wise unit sold",
        "BHK type wise average carpet area",
        "BHK type wise unit sold",
        "Carpet area sold or consumed",
        "Property type wise Carpet area sold or consumed",
        "Property type wise area range wise Carpet area sold or consumed",
        "Property type wise area range wise total sales analysis (INR)",
        "Property type wise area range wise unit sold",
        "Property type wise average carpet area",
        "Property type wise unit sold",
        "Units Sold",
        "broad property type wise Carpet area sold or consumed",
        "broad property types wise unit sold",
    ],
    "demography": [
        "BHK type wise Age Range wise carpet area sold or consumed",
        "BHK type wise Age Range wise total sales (INR)",
        "BHK type wise Age Range wise units sold",
        "BHK type wise top buuyers pincode wise Carpet area sold or consumed",
        "BHK type wise top buuyers pincode wise total sales (INR)",
        "BHK type wise top buuyers pincode wise unit sold",
        "Property type wise Age Range wise carpet area sold or consumed",
        "Property type wise Age Range wise total sales (INR)",
        "Property type wise Age Range wise units sold",
        "Property type wise top buuyers pincode wise Carpet area sold or consumed",
        "Property type wise top buuyers pincode wise total sales (INR)",
        "Property type wise top buuyers pincode wise unit sold",
        "Top 10 Buyer Pincode",
        "Top buyer pincode",
    ],
    "price": [
        "BHK type wise Price (/sqft) range wise Units sold",
        "BHK type wise Price (/sqft) range wise carpet area sold or consumed",
        "BHK type wise Price (/sqft) range wise total sales (INR)",
        "BHK type wise total price range wise  carpet area sold or consumed",
        "BHK type wise total price range wise total sales (INR)",
        "BHK type wise total price range wise unit sold",
        "BHK wise Total sales (INR)",
        "BHK wise average price (INR)",
        "Property Type Wise Average Price per Sq. Ft. (Carpet Area Basis)",
        "Property Type Wise Percentile's Price per Sq. Ft. (Carpet Area Basis)",
        "Property Type Wise most prevailing Price per Sq. Ft. (Carpet Area Basis)",
        "Property type wise Average Price (INR)",
        "Property type wise Price (/sqft) range wise Units sold",
        "Property type wise Price (/sqft) range wise carpet area sold or consumed",
        "Property type wise Price (/sqft) range wise total sales (INR)",
        "Property type wise Total Sales (INR)",
        "Property type wise total price range wise  carpet area sold or consumed",
        "Property type wise total price range wise total sales (INR)",
        "Property type wise total price range wise unit sold",
        "Total sales (INR)",
        "broad property type wise average price (INR)",
        "broad property type wise total sales (INR)",
    ],
    "supply": [
        "BHK type wise total carpet area",
        "BHK type wise total units",
        "Property type wise total carpet area",
        "Property type wise total units",
        "Total Carpet Area",
        "Total FSI in Sqft",
        "Total Number of Units",
        "Total Plot Area in Sqmtr",
    ],
}